version: '3.0'
services:
  fragment:
    image: oneseismic.azurecr.io/base:${VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    command: [
        "oneseismic-fetch",
        "--redis-url",  "storage:6379",
        "--retries",  "1",
    ]
    depends_on:
      - storage

  result:
    image: oneseismic.azurecr.io/base:${VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080'
    command: [
        "oneseismic-result",
        "--redis-url", "storage:6379",
    ]
    depends_on:
      - storage
    environment:
      - SIGN_KEY

  api:
    image: oneseismic.azurecr.io/base:${VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080'
    command: [
        "oneseismic-query",
    ]
    depends_on:
      - storage
    environment:
      - STORAGE_URL
      - CLIENT_ID
      - LOG_LEVEL
      - REDIS_URL=storage:6379
      - SIGN_KEY

  storage:
    image: redis

  server:
    image: nginx:latest
    ports:
      - 8080:8080
    volumes:
      - ./docker-compose-nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - result
