name: Wheels

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macOS-10.15]
        include:
          - os: windows-2019
            cibw-arch: AMD64
            cmake-generator: "Visual Studio 16 2019"
            cmake_generator_platform: "x64"
          - os: windows-2019
            cibw-arch: x86
            cmake-generator: "Visual Studio 16 2019"
            cmake_generator_platform: "Win32"

    steps:
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: Build wheels
        env:
          CIBW_ENVIRONMENT_WINDOWS: >
            CMAKE_GENERATOR="${{ matrix.cmake-generator }}"
            CMAKE_GENERATOR_PLATFORM="${{ matrix.cmake_generator_platform }}"

          CIBW_ARCHS_WINDOWS: ${{ matrix.cibw-arch }}
          COMSPEC: C:\Program Files\PowerShell\7\pwsh.EXE
        run: |
            python -m cibuildwheel --output-dir wheelhouse python/

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
